"""Add check_in_focus to development milestones

Revision ID: 261a61880013
Revises: c769a6970707
Create Date: 2026-05-05 22:06:17.144127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261a61880013'
down_revision: Union[str, None] = 'c769a6970707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('development_milestones', sa.Column('check_in_focus', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('development_milestones', 'check_in_focus')
    # ### end Alembic commands ###
