"""Add development plans and milestones

Revision ID: c769a6970707
Revises: 20260505_0013
Create Date: 2026-05-05 22:05:12.218699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c769a6970707'
down_revision: Union[str, None] = '20260505_0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('development_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('development_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_skills', sa.JSON(), nullable=False),
    sa.Column('learning_resources', sa.JSON(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outcome_score', sa.Float(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['development_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skill_synonyms')
    op.drop_index(op.f('idx_audit_org'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('idx_notif_employee'), table_name='notifications')
    op.drop_index(op.f('idx_notif_org'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('idx_qbank_audience'), table_name='question_bank', postgresql_using='gin')
    op.drop_index(op.f('idx_qbank_skill'), table_name='question_bank')
    op.drop_index(op.f('idx_qbank_status'), table_name='question_bank')
    op.drop_index(op.f('idx_qbank_type'), table_name='question_bank')
    op.drop_table('question_bank')
    op.create_foreign_key(None, 'projects', 'job_descriptions', ['jd_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_psychometric_results_employee'), table_name='psychometric_results')
    op.drop_index(op.f('ix_psychometric_results_org'), table_name='psychometric_results')
    op.drop_index(op.f('idx_skills_sector_tags'), table_name='skills', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_skills_sector_tags'), 'skills', ['sector_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_psychometric_results_org'), 'psychometric_results', ['org_id'], unique=False)
    op.create_index(op.f('ix_psychometric_results_employee'), 'psychometric_results', ['employee_id'], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_table('question_bank',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=30), server_default=sa.text("'mcq'::character varying"), autoincrement=False, nullable=True),
    sa.Column('bloom_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('difficulty_target', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('audience_type', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('irt_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irt_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irt_c', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.25'::double precision"), autoincrement=False, nullable=True),
    sa.Column('calibration_status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('pilot_response_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('real_b_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_a_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sme_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('adverse_impact_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('exposure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('exposure_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('parent_question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('technology_version_lock', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_question_id'], ['question_bank.id'], name=op.f('question_bank_parent_question_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('question_bank_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('question_bank_pkey'))
    )
    op.create_index(op.f('idx_qbank_type'), 'question_bank', ['question_type'], unique=False)
    op.create_index(op.f('idx_qbank_status'), 'question_bank', ['calibration_status'], unique=False)
    op.create_index(op.f('idx_qbank_skill'), 'question_bank', ['skill_id'], unique=False)
    op.create_index(op.f('idx_qbank_audience'), 'question_bank', ['audience_type'], unique=False, postgresql_using='gin')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('sent_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('notifications_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('notifications_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notif_org'), 'notifications', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_notif_employee'), 'notifications', ['employee_id', 'is_read'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('records_pulled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('sync_logs_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_logs_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('audit_logs_employee_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('audit_logs_org_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_org'), 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.create_table('skill_synonyms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('synonym', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_synonyms_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_synonyms_pkey')),
    sa.UniqueConstraint('skill_id', 'synonym', name=op.f('skill_synonyms_skill_id_synonym_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('development_milestones')
    op.drop_table('development_plans')
    # ### end Alembic commands ###
