"""Add Skill CAT and Evidence tables

Revision ID: d722c8739a78
Revises: 20260416_0006
Create Date: 2026-04-23 16:35:31.126620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd722c8739a78'
down_revision: Union[str, None] = '20260416_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), server_default='mcq', nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer_id', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('a_param', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('b_param', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('c_param', sa.Float(), server_default='0.25', nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=True),
    sa.Column('audience_type', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('calibration_status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('exposure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessment_responses', sa.Column('se_before', sa.Float(), nullable=True))
    op.add_column('assessment_responses', sa.Column('se_after', sa.Float(), nullable=True))
    op.alter_column('assessment_responses', 'selected_option_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'response_time_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_responses_session'), table_name='assessment_responses')
    op.drop_constraint(op.f('assessment_responses_question_id_fkey'), 'assessment_responses', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_responses', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assessment_responses', 'question_sequence')
    op.drop_column('assessment_responses', 'llm_scored_at')
    op.drop_column('assessment_responses', 'llm_score')
    op.drop_column('assessment_responses', 'score')
    op.drop_column('assessment_responses', 'llm_score_rationale')
    op.add_column('assessment_sessions', sa.Column('administered_question_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    op.alter_column('assessment_sessions', 'current_theta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('assessment_sessions', 'current_se',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('assessment_sessions', 'questions_served',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('assessment_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('assessment_sessions', 'response_pattern_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_sessions_assessment'), table_name='assessment_sessions')
    op.drop_index(op.f('idx_sessions_employee'), table_name='assessment_sessions')
    op.drop_index(op.f('idx_sessions_status'), table_name='assessment_sessions')
    op.drop_column('assessment_sessions', 'avg_response_time_seconds')
    op.drop_column('assessment_sessions', 'percentage_score')
    op.drop_column('assessment_sessions', 'final_theta')
    op.drop_column('assessment_sessions', 'created_at')
    op.drop_column('assessment_sessions', 'flagged_for_review')
    op.drop_column('assessment_sessions', 'raw_score')
    op.drop_column('assessment_sessions', 'passed')
    op.drop_column('assessment_sessions', 'updated_at')
    op.drop_column('assessment_sessions', 'pass_threshold')
    op.drop_constraint(op.f('assessments_role_profile_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('assessments_created_by_fkey'), 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'is_adaptive')
    op.drop_column('assessments', 'due_date')
    op.drop_column('assessments', 'created_at')
    op.drop_column('assessments', 'time_limit_minutes')
    op.drop_column('assessments', 'skill_ids')
    op.drop_column('assessments', 'is_proctored')
    op.drop_column('assessments', 'audience_type')
    op.drop_column('assessments', 'assessment_type')
    op.drop_column('assessments', 'max_questions')
    op.drop_column('assessments', 'created_by')
    op.drop_column('assessments', 'description')
    op.drop_column('assessments', 'role_profile_id')
    op.drop_column('assessments', 'updated_at')
    op.drop_column('assessments', 'status')
    op.drop_column('assessments', 'is_mandatory')
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_dept_head_employee'), 'departments', type_='foreignkey')
    op.alter_column('employee_skill_scores', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('employee_skill_scores_employee_id_skill_id_key'), 'employee_skill_scores', type_='unique')
    op.drop_index(op.f('idx_emp_skill_scores_employee'), table_name='employee_skill_scores')
    op.drop_index(op.f('idx_emp_skill_scores_skill'), table_name='employee_skill_scores')
    op.drop_column('employee_skill_scores', 'source_diversity')
    op.drop_column('employee_skill_scores', 'manager_rating_date')
    op.drop_column('employee_skill_scores', 'created_at')
    op.drop_column('employee_skill_scores', 'score_validated')
    op.drop_column('employee_skill_scores', 'updated_at')
    op.drop_column('employee_skill_scores', 'theta_score')
    op.drop_column('employee_skill_scores', 'manager_rating')
    op.drop_column('employee_skill_scores', 'first_evidence_at')
    op.drop_column('employee_skill_scores', 'last_evidence_at')
    op.alter_column('employees', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'full_time'::character varying"))
    op.alter_column('employees', 'consent_github',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_email',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_teams',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_slack',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'employment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('integration_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('integration_configs', 'sync_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'daily'::character varying"))
    op.alter_column('integration_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('integration_configs_org_id_integration_type_key'), 'integration_configs', type_='unique')
    op.alter_column('organizations', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'IN'::character varying"))
    op.alter_column('organizations', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'max_employees',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('organizations', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'data_residency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'cloud'::character varying"))
    op.alter_column('organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('organizations', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('organizations', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_profiles', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('role_profiles', 'calibrated_from_top_performers',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('role_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('role_required_skills', sa.Column('required_proficiency', sa.Float(), nullable=False))
    op.alter_column('role_required_skills', 'criticality',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'important'::character varying"))
    op.alter_column('role_required_skills', 'is_compliance',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('role_required_skills_role_profile_id_skill_id_key'), 'role_required_skills', type_='unique')
    op.drop_column('role_required_skills', 'criticality_weight')
    op.drop_column('role_required_skills', 'created_at')
    op.drop_column('role_required_skills', 'expiry_tracking')
    op.drop_column('role_required_skills', 'min_proficiency')
    op.add_column('skill_evidence', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('skill_evidence', 'decay_half_life_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('365'))
    op.alter_column('skill_evidence', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('skill_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_evidence_employee'), table_name='skill_evidence')
    op.drop_index(op.f('idx_evidence_observed'), table_name='skill_evidence')
    op.drop_index(op.f('idx_evidence_skill'), table_name='skill_evidence')
    op.drop_index(op.f('idx_evidence_source'), table_name='skill_evidence')
    op.drop_column('skill_evidence', 'source_system')
    op.drop_column('skill_evidence', 'extraction_method')
    op.drop_column('skill_evidence', 'source_record_id')
    op.drop_column('skill_evidence', 'evidence_url')
    op.drop_column('skill_evidence', 'is_flagged')
    op.drop_column('skill_evidence', 'extracted_at')
    op.drop_column('skill_evidence', 'llm_model_used')
    op.drop_column('skill_evidence', 'sentiment')
    op.drop_index(op.f('idx_gaps_employee'), table_name='skill_gaps')
    op.drop_index(op.f('idx_gaps_priority'), table_name='skill_gaps', postgresql_where="((status)::text = 'open'::text)")
    op.drop_constraint(op.f('skill_gaps_employee_id_role_profile_id_skill_id_key'), 'skill_gaps', type_='unique')
    op.drop_column('skill_gaps', 'closed_at')
    op.drop_column('skill_gaps', 'recommended_actions')
    op.drop_column('skill_gaps', 'updated_at')
    op.drop_column('skill_gaps', 'computed_at')
    op.alter_column('skills', 'is_compliance',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_skills_canonical'), table_name='skills')
    op.drop_index(op.f('idx_skills_domain'), table_name='skills')
    op.drop_index(op.f('idx_skills_sector_tags'), table_name='skills', postgresql_using='gin')
    op.drop_constraint(op.f('skills_esco_uri_key'), 'skills', type_='unique')
    op.drop_constraint(op.f('skills_parent_skill_id_fkey'), 'skills', type_='foreignkey')
    op.drop_column('skills', 'bloom_level')
    op.drop_column('skills', 'skill_type')
    op.drop_column('skills', 'sector_tags')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'synonyms')
    op.drop_column('skills', 'description')
    op.drop_column('skills', 'parent_skill_id')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'source')
    op.drop_column('skills', 'is_emerging')
    op.drop_column('skills', 'esco_uri')
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'is_sso',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_sso',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('skills', sa.Column('esco_uri', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('is_emerging', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'esco'::character varying"), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('parent_skill_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('synonyms', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('sector_tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('skill_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('bloom_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('skills_parent_skill_id_fkey'), 'skills', 'skills', ['parent_skill_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('skills_esco_uri_key'), 'skills', ['esco_uri'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_skills_sector_tags'), 'skills', ['sector_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_skills_domain'), 'skills', ['domain'], unique=False)
    op.create_index(op.f('idx_skills_canonical'), 'skills', ['canonical_name'], unique=False)
    op.alter_column('skills', 'is_compliance',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('skill_gaps', sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skill_gaps', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skill_gaps', sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('skill_gaps', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('skill_gaps_employee_id_role_profile_id_skill_id_key'), 'skill_gaps', ['employee_id', 'role_profile_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_gaps_priority'), 'skill_gaps', ['priority_score'], unique=False, postgresql_where="((status)::text = 'open'::text)")
    op.create_index(op.f('idx_gaps_employee'), 'skill_gaps', ['employee_id'], unique=False)
    op.add_column('skill_evidence', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('llm_model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('is_flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('evidence_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('source_record_id', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('extraction_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('skill_evidence', sa.Column('source_system', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_evidence_source'), 'skill_evidence', ['source_type'], unique=False)
    op.create_index(op.f('idx_evidence_skill'), 'skill_evidence', ['skill_id'], unique=False)
    op.create_index(op.f('idx_evidence_observed'), 'skill_evidence', ['observed_at'], unique=False)
    op.create_index(op.f('idx_evidence_employee'), 'skill_evidence', ['employee_id'], unique=False)
    op.alter_column('skill_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skill_evidence', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('skill_evidence', 'decay_half_life_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('365'))
    op.drop_column('skill_evidence', 'metadata_json')
    op.add_column('role_required_skills', sa.Column('min_proficiency', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'3'::double precision"), autoincrement=False, nullable=False))
    op.add_column('role_required_skills', sa.Column('expiry_tracking', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('role_required_skills', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('role_required_skills', sa.Column('criticality_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('role_required_skills_role_profile_id_skill_id_key'), 'role_required_skills', ['role_profile_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('role_required_skills', 'is_compliance',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('role_required_skills', 'criticality',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'important'::character varying"))
    op.drop_column('role_required_skills', 'required_proficiency')
    op.alter_column('role_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_profiles', 'calibrated_from_top_performers',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('role_profiles', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('organizations', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('organizations', 'data_residency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cloud'::character varying"))
    op.alter_column('organizations', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'max_employees',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('organizations', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('organizations', 'country',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'IN'::character varying"))
    op.create_unique_constraint(op.f('integration_configs_org_id_integration_type_key'), 'integration_configs', ['org_id', 'integration_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('integration_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_configs', 'sync_frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'daily'::character varying"))
    op.alter_column('integration_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('integration_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'employment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('employees', 'consent_slack',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_teams',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_email',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'consent_github',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'full_time'::character varying"))
    op.add_column('employee_skill_scores', sa.Column('last_evidence_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('first_evidence_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('manager_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('theta_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('score_validated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('manager_rating_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('employee_skill_scores', sa.Column('source_diversity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_emp_skill_scores_skill'), 'employee_skill_scores', ['skill_id'], unique=False)
    op.create_index(op.f('idx_emp_skill_scores_employee'), 'employee_skill_scores', ['employee_id'], unique=False)
    op.create_unique_constraint(op.f('employee_skill_scores_employee_id_skill_id_key'), 'employee_skill_scores', ['employee_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employee_skill_scores', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(op.f('fk_dept_head_employee'), 'departments', 'employees', ['head_employee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('assessments', sa.Column('is_mandatory', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('role_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('max_questions', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('assessment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('audience_type', sa.VARCHAR(length=50), server_default=sa.text("'all'::character varying"), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('is_proctored', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('skill_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('time_limit_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('is_adaptive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assessments_created_by_fkey'), 'assessments', 'employees', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('assessments_role_profile_id_fkey'), 'assessments', 'role_profiles', ['role_profile_id'], ['id'], ondelete='SET NULL')
    op.add_column('assessment_sessions', sa.Column('pass_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'3'::double precision"), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('raw_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('flagged_for_review', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('final_theta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('percentage_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_sessions', sa.Column('avg_response_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_sessions_status'), 'assessment_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_sessions_employee'), 'assessment_sessions', ['employee_id'], unique=False)
    op.create_index(op.f('idx_sessions_assessment'), 'assessment_sessions', ['assessment_id'], unique=False)
    op.alter_column('assessment_sessions', 'response_pattern_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('assessment_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('assessment_sessions', 'questions_served',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('assessment_sessions', 'current_se',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('assessment_sessions', 'current_theta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('assessment_sessions', 'administered_question_ids')
    op.add_column('assessment_responses', sa.Column('llm_score_rationale', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assessment_responses', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_responses', sa.Column('llm_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('assessment_responses', sa.Column('llm_scored_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('assessment_responses', sa.Column('question_sequence', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessment_responses', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_responses_question_id_fkey'), 'assessment_responses', 'question_bank', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_responses_session'), 'assessment_responses', ['session_id'], unique=False)
    op.alter_column('assessment_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_responses', 'response_time_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_responses', 'selected_option_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('assessment_responses', 'se_after')
    op.drop_column('assessment_responses', 'se_before')
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('records_pulled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('sync_logs_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_logs_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('sent_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('notifications_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('notifications_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notif_org'), 'notifications', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_notif_employee'), 'notifications', ['employee_id', 'is_read'], unique=False)
    op.create_table('question_bank',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=30), server_default=sa.text("'mcq'::character varying"), autoincrement=False, nullable=True),
    sa.Column('bloom_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('difficulty_target', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('audience_type', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('irt_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irt_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('irt_c', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.25'::double precision"), autoincrement=False, nullable=True),
    sa.Column('calibration_status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('pilot_response_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('real_b_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_a_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sme_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('adverse_impact_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('exposure_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('exposure_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('parent_question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('technology_version_lock', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_question_id'], ['question_bank.id'], name=op.f('question_bank_parent_question_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('question_bank_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('question_bank_pkey'))
    )
    op.create_index(op.f('idx_qbank_type'), 'question_bank', ['question_type'], unique=False)
    op.create_index(op.f('idx_qbank_status'), 'question_bank', ['calibration_status'], unique=False)
    op.create_index(op.f('idx_qbank_skill'), 'question_bank', ['skill_id'], unique=False)
    op.create_index(op.f('idx_qbank_audience'), 'question_bank', ['audience_type'], unique=False, postgresql_using='gin')
    op.create_table('skill_synonyms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('synonym', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_synonyms_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_synonyms_pkey')),
    sa.UniqueConstraint('skill_id', 'synonym', name=op.f('skill_synonyms_skill_id_synonym_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('audit_logs_employee_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('audit_logs_org_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_org'), 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.drop_table('questions')
    # ### end Alembic commands ###
